### ISSUE TITLE
Can't compile after fixing audit versions `_this.addWatchFile is not a function`

### ISSUE THREAD

**Issue by drpain** [egoist/rollup-plugin-postcss#196] opened 2019-09-13 12:59 UTC
```
[!] (postcss plugin) TypeError: _this.addWatchFile is not a function
src/index.scss
TypeError: _this.addWatchFile is not a function
    at /home/rudis1261/Projects/onboarding/order_ecosystem/order-fe/node_modules/rollup-plugin-postcss-modules/node_modules/rollup-plugin-postcss/dist/index.js:723:19
```

**Comment by Himself65** [comment] 2020-03-07 08:08
can you update it to the latest version? or give us more detail to reproduce the bug

**Comment by wardpeet** [comment] 2020-08-30 21:10
Thank you for opening the issue, we haven't got any more issues around this problem for a while. We moved to rollup version 2 as a required version, so I'm closing this bug because it doesn't seem relevant anymore.

If this is not the case, please re-open or create a new ticket with new information. Thank you!

**Closed by wardpeet** 2020-08-30 21:10 UTC
Labels: bug
