### ISSUE TITLE
Rollup Tree Shaking remove styleInject

### ISSUE THREAD

**Issue by markstock7** [egoist/rollup-plugin-postcss#183] opened 2019-07-26 04:52 UTC
I want to inject my css into bundle.js. But if i enable tree shaking, rollup will remove styleInject that postcss created.

````
 function styleInject(css, ref) {
      if ( ref === void 0 ) { ref = {}; }
      var insertAt = ref.insertAt;

      if (!css || typeof document === 'undefined') { return; }

      var head = document.head || document.getElementsByTagName('head')[0];
      var style = document.createElement('style');
      style.type = 'text/css';

      if (insertAt === 'top') {
        if (head.firstChild) {
          head.insertBefore(style, head.firstChild);
        } else {
          head.appendChild(style);
        }
      } else {
        head.appendChild(style);
      }

      if (style.styleSheet) {
        style.styleSheet.cssText = css;
      } else {
        style.appendChild(document.createTextNode(css));
      }
    }

    var css = "._gio_c_modal{padding:20px;display:inline-block;overflow:hidden;position:relative;background:#fff;border-radius:3px;z-index:2147483646;-webkit-box-shadow:0 4px 6px 0 hsla(0,0%,43.9%,.5);box-shadow:0 4px 6px 0 hsla(0,0%,43.9%,.5)}._gio_c_modal,._gio_c_modal *{-webkit-box-sizing:border-box;box-sizing:border-box}._gio_c_modal__close{z-index:2147483647;top:10px;right:10px;position:absolute;cursor:pointer}._gio_c_modal_center{width:388px}._gio_c_img{position:relative;width:inherit;margin:-20px -20px 0}._gio_c_paragraph{font-size:12px;margin-bottom:10px}._gio_c_btn{font-size:14px;max-height:100px;font-weight:500;margin:0 auto;cursor:pointer;display:block;background-image:none;border:1px solid transparent;white-space:nowrap;line-height:1.5;padding:4px 15px;-webkit-transition:all .3s cubic-bezier(.645,.045,.355,1) 0s;-o-transition:all .3s cubic-bezier(.645,.045,.355,1) 0s;transition:all .3s cubic-bezier(.645,.045,.355,1) 0s;position:relative;color:#fff;height:36px;width:159px;border-radius:2px;background-color:#fc5f3a;max-width:100%}._gio_c_caption{margin:10px 0;text-align:center;font-size:18px;font-weight:500}.gio-modal-anchor-top{position:absolute;top:0}.gio-modal-anchor-center{display:table-cell;vertical-align:middle;text-align:center;margin:0;padding:0}.gio-modal-anchor-lb{bottom:20px;left:20px;position:fixed;z-index:2147483647}#gio-modal-wrapper-outter{width:100%;height:100%;display:table;position:fixed;top:0;left:0;z-index:2147483646}#_gio_c_modal_mask{width:100%;height:100%;background:#000;position:absolute;top:0;left:0;opacity:.4;z-index:2147483645;-moz-user-select:none;-webkit-user-select:none}";
    styleInject(css);
````

js using import to get less

`
import '../stylesheets/index.less'
`

**Comment by rpearce** [comment] 2019-11-21 04:38
Seems like a duplicate of https://github.com/egoist/rollup-plugin-postcss/issues/165?

See https://github.com/egoist/rollup-plugin-postcss/pull/199 for potential PR that fixes this...

**Closed** 2019-12-27 08:15 UTC
